package fr.atlantique.imt.inf211.jobmngt.entity;
// default package
// Generated 8 mars 2025, 23:37:20 by Hibernate Tools 5.6.15.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Candidature generated by hbm2java
 */
@Entity
@Table(name="candidature"
    ,schema="public"
)
public class Candidature  implements java.io.Serializable {


     private int idCandidature;
     private Candidat candidat;
     private QualificationLevel qualificationLevel;
     private String cv;
     private Date appDate;
     private Set<MessageCandidature> messageCandidatures = new HashSet<MessageCandidature>(0);
     private Set<MessageOffre> messageOffres = new HashSet<MessageOffre>(0);
     private Set<Sector> sectors = new HashSet<Sector>(0);

    public Candidature() {
    }

	
    public Candidature(int idCandidature, Candidat candidat, QualificationLevel qualificationLevel, String cv, Date appDate) {
        this.idCandidature = idCandidature;
        this.candidat = candidat;
        this.qualificationLevel = qualificationLevel;
        this.cv = cv;
        this.appDate = appDate;
    }
    public Candidature(int idCandidature, Candidat candidat, QualificationLevel qualificationLevel, String cv, Date appDate, Set<MessageCandidature> messageCandidatures, Set<MessageOffre> messageOffres, Set<Sector> sectors) {
       this.idCandidature = idCandidature;
       this.candidat = candidat;
       this.qualificationLevel = qualificationLevel;
       this.cv = cv;
       this.appDate = appDate;
       this.messageCandidatures = messageCandidatures;
       this.messageOffres = messageOffres;
       this.sectors = sectors;
    }
   
    @Id
    @SequenceGenerator(name = "CANDIDATURE_ID_GENERATOR", sequenceName = "CANDIDATURE_ID_SEQ", allocationSize = 1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CANDIDATURE_ID_GENERATOR")
    @Column(name="idcandidature", unique=true, nullable=false)
    public int getIdCandidature() {
        return this.idCandidature;
    }
    
    public void setIdCandidature(int idCandidature) {
        this.idCandidature = idCandidature;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcandidat", nullable=false)
    public Candidat getCandidat() {
        return this.candidat;
    }
    
    public void setCandidat(Candidat candidat) {
        this.candidat = candidat;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idqualification", nullable=false)
    public QualificationLevel getQualificationLevel() {
        return this.qualificationLevel;
    }
    
    public void setQualificationLevel(QualificationLevel qualificationLevel) {
        this.qualificationLevel = qualificationLevel;
    }

    
    @Column(name="cv", nullable=false)
    public String getCv() {
        return this.cv;
    }
    
    public void setCv(String cv) {
        this.cv = cv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="appdate", nullable=false, length=13)
    public Date getAppDate() {
        return this.appDate;
    }
    
    public void setAppDate(Date appDate) {
        this.appDate = appDate;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="candidature")
    public Set<MessageCandidature> getMessageCandidatures() {
        return this.messageCandidatures;
    }
    
    public void setMessageCandidatures(Set<MessageCandidature> messageCandidatures) {
        this.messageCandidatures = messageCandidatures;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="candidature")
    public Set<MessageOffre> getMessageOffres() {
        return this.messageOffres;
    }
    
    public void setMessageOffres(Set<MessageOffre> messageOffres) {
        this.messageOffres = messageOffres;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="candidaturesecteur", schema="public", joinColumns = { 
    @JoinColumn(name="idcandidature", nullable=false, updatable=false) }, inverseJoinColumns = { 
    @JoinColumn(name="idsecteur", nullable=false, updatable=false) })
    public Set<Sector> getSectors() {
        return this.sectors;
    }
    
    public void setSectors(Set<Sector> sectors) {
        this.sectors = sectors;
    }

}


