package fr.atlantique.imt.inf211.jobmngt.entity;
// default package
// Generated 8 mars 2025, 23:37:20 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Candidat generated by hbm2java
 */
@JsonIdentityInfo(
  generator = ObjectIdGenerators.PropertyGenerator.class,
  property = "idCandidat")
@Entity
@Table(name="candidat"
    ,schema="public"
)
public class Candidat  implements java.io.Serializable {


     private int idCandidat;
     private AppUser appUser;
     private String firstName;
     private String lastName;
     private Set<Candidature> candidatures = new HashSet<Candidature>(0);

    public Candidat() {
    }

	
    public Candidat(AppUser appUser, String firstName, String lastName) {
        this.appUser = appUser;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public Candidat(AppUser appUser, String firstName, String lastName, Set<Candidature> candidatures) {
       this.appUser = appUser;
       this.firstName = firstName;
       this.lastName = lastName;
       this.candidatures = candidatures;
    }
   
    @GenericGenerator(name="CandidatIdGenerator", strategy="foreign", parameters=@Parameter(name="property", value="appuser"))
    @Id
    @GeneratedValue(generator="CandidatIdGenerator")
    @Column(name="idcandidat", unique=true, nullable=false)
    public int getIdCandidat() {
        return this.idCandidat;
    }
    
    public void setIdCandidat(int idCandidat) {
        this.idCandidat = idCandidat;
    }

    @OneToOne(fetch=FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public AppUser getAppUser() {
        return this.appUser;
    }
    
    public void setAppUser(AppUser appUser) {
        this.appUser = appUser;
    }

    
    @Column(name="firstname", nullable=false, length=50)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="lastname", nullable=false, length=50)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="candidat")
    public Set<Candidature> getCandidatures() {
        return this.candidatures;
    }
    
    public void setCandidatures(Set<Candidature> candidatures) {
        this.candidatures = candidatures;
    }




}


