package fr.atlantique.imt.inf211.jobmngt.entity;
// default package
// Generated 8 mars 2025, 23:37:20 by Hibernate Tools 5.6.15.Final


import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * Entreprise generated by hbm2java
 */
@JsonIdentityInfo(
  generator = ObjectIdGenerators.PropertyGenerator.class,
  property = "idEntreprise")
@Entity
@Table(name="entreprise"
    ,schema="public"
)
public class Entreprise  implements java.io.Serializable {


     private int idEntreprise;
     private AppUser appUser;
     private String denomination;
     private String description;
     private Set<OffreEmploi> offreEmplois = new HashSet<OffreEmploi>(0);

    public Entreprise() {
    }

	
    public Entreprise(AppUser appUser, String denomination) {
        this.appUser = appUser;
        this.denomination = denomination;
    }
    public Entreprise(AppUser appUser, String denomination, String description, Set<OffreEmploi> offreEmplois) {
       this.appUser = appUser;
       this.denomination = denomination;
       this.description = description;
       this.offreEmplois = offreEmplois;
    }
   
    @GenericGenerator(name="EntrepriseIdGenerator", strategy="foreign", parameters=@Parameter(name="property", value="appuser"))
    @Id
    @GeneratedValue(generator="EntrepriseIdGenerator")
    @Column(name="identreprise", unique=true, nullable=false)
    public int getIdEntreprise() {
        return this.idEntreprise;
    }
    
    public void setIdEntreprise(int idEntreprise) {
        this.idEntreprise = idEntreprise;
    }

    @OneToOne(fetch=FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public AppUser getAppUser() {
        return this.appUser;
    }
    
    public void setAppUser(AppUser appUser) {
        this.appUser = appUser;
    }

    
    @Column(name="denomination", nullable=false, length=100)
    public String getDenomination() {
        return this.denomination;
    }
    
    public void setDenomination(String denomination) {
        this.denomination = denomination;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="entreprise")
    public Set<OffreEmploi> getOffreEmplois() {
        return this.offreEmplois;
    }
    
    public void setOffreEmplois(Set<OffreEmploi> offreEmplois) {
        this.offreEmplois = offreEmplois;
    }




}


