package fr.atlantique.imt.inf211.jobmngt.entity;
// default package
// Generated 8 mars 2025, 23:37:20 by Hibernate Tools 5.6.15.Final


import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Messageoffre generated by hbm2java
 */
@Entity
@Table(name="messageoffre"
    ,schema="public"
)
public class MessageOffre  implements java.io.Serializable {


     private int idMessageOffre;
     private Candidature candidature;
     private OffreEmploi offreEmploi;
     private String message;
     private Date publicationDate;

    public MessageOffre() {
    }

	
    public MessageOffre(int idMessageOffre, OffreEmploi offreEmploi, String message, Date publicationDate) {
        this.idMessageOffre = idMessageOffre;
        this.offreEmploi = offreEmploi;
        this.message = message;
        this.publicationDate = publicationDate;
    }
    public MessageOffre(int idMessageOffre, Candidature candidature, OffreEmploi offreEmploi, String message, Date publicationDate) {
       this.idMessageOffre = idMessageOffre;
       this.candidature = candidature;
       this.offreEmploi = offreEmploi;
       this.message = message;
       this.publicationDate = publicationDate;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)    
    @Column(name="idmessageoffre", unique=true, nullable=false)
    public int getIdMessageOffre() {
        return this.idMessageOffre;
    }
    
    public void setIdMessageOffre(int idMessageOffre) {
        this.idMessageOffre = idMessageOffre;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcandidature")
    public Candidature getCandidature() {
        return this.candidature;
    }
    
    public void setCandidature(Candidature candidature) {
        this.candidature = candidature;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idoffreemploi", nullable=false)
    public OffreEmploi getOffreEmploi() {
        return this.offreEmploi;
    }
    
    public void setOffreEmploi(OffreEmploi offreEmploi) {
        this.offreEmploi = offreEmploi;
    }

    
    @Column(name="message", nullable=false)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="publicationdate", nullable=false, length=13)
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }




}


