package fr.atlantique.imt.inf211.jobmngt.entity;
// default package
// Generated 8 mars 2025, 23:37:20 by Hibernate Tools 5.6.15.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Offreemploi generated by hbm2java
 */
@JsonIdentityInfo(
  generator = ObjectIdGenerators.PropertyGenerator.class,
  property = "idOffreEmploi")
@Entity
@Table(name="offreemploi"
    ,schema="public"
)
public class OffreEmploi  implements java.io.Serializable {


     private int idOffreEmploi;
     private Entreprise entreprise;
     private QualificationLevel qualificationLevel;
     private String title;
     private String taskDescription;
     private Date publicationDate;
     private Set<Sector> sectors = new HashSet<Sector>(0);
     private Set<MessageCandidature> messageCandidatures = new HashSet<MessageCandidature>(0);
     private Set<MessageOffre> messageOffres = new HashSet<MessageOffre>(0);

    public OffreEmploi() {
    }

	
    public OffreEmploi(int idOffreEmploi, Entreprise entreprise, QualificationLevel qualificationLevel, String title, String taskDescription, Date publicationDate) {
        this.idOffreEmploi = idOffreEmploi;
        this.entreprise = entreprise;
        this.qualificationLevel = qualificationLevel;
        this.title = title;
        this.taskDescription = taskDescription;
        this.publicationDate = publicationDate;
    }
    public OffreEmploi(int idOffreEmploi, Entreprise entreprise, QualificationLevel qualificationLevel, String title, String taskDescription, Date publicationDate, Set<Sector> sectors, Set<MessageCandidature> messageCandidatures, Set<MessageOffre> messageOffres) {
       this.idOffreEmploi = idOffreEmploi;
       this.entreprise = entreprise;
       this.qualificationLevel = qualificationLevel;
       this.title = title;
       this.taskDescription = taskDescription;
       this.publicationDate = publicationDate;
       this.sectors = sectors;
       this.messageCandidatures = messageCandidatures;
       this.messageOffres = messageOffres;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)    
    @Column(name="idoffreemploi", unique=true, nullable=false)
    public int getIdOffreEmploi() {
        return this.idOffreEmploi;
    }
    
    public void setIdOffreEmploi(int idOffreEmploi) {
        this.idOffreEmploi = idOffreEmploi;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="identreprise", nullable=false)
    public Entreprise getEntreprise() {
        return this.entreprise;
    }
    
    public void setEntreprise(Entreprise entreprise) {
        this.entreprise = entreprise;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idqualification", nullable=false)
    public QualificationLevel getQualificationLevel() {
        return this.qualificationLevel;
    }
    
    public void setQualificationLevel(QualificationLevel qualificationLevel) {
        this.qualificationLevel = qualificationLevel;
    }

    
    @Column(name="title", nullable=false, length=100)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="taskdescription", nullable=false)
    public String getTaskDescription() {
        return this.taskDescription;
    }
    
    public void setTaskDescription(String taskDescription) {
        this.taskDescription = taskDescription;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="publicationdate", nullable=false, length=13)
    public Date getPublicationDate() {
        return this.publicationDate;
    }
    
    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="emploisecteur", schema="public", joinColumns = { 
    @JoinColumn(name="idoffreemploi", nullable=false, updatable=false) }, inverseJoinColumns = { 
    @JoinColumn(name="idsecteur", nullable=false, updatable=false) })
    public Set<Sector> getSectors() {
        return this.sectors;
    }
    
    public void setSectors(Set<Sector> sectors) {
        this.sectors = sectors;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="offreEmploi")
    public Set<MessageCandidature> getMessageCandidatures() {
        return this.messageCandidatures;
    }
    
    public void setMessageCandidatures(Set<MessageCandidature> messageCandidatures) {
        this.messageCandidatures = messageCandidatures;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="offreEmploi")
    public Set<MessageOffre> getMessageOffres() {
        return this.messageOffres;
    }
    
    public void setMessageOffres(Set<MessageOffre> messageOffres) {
        this.messageOffres = messageOffres;
    }




}


